export const MODULE_CATALOG = [
  { n: 1, badge: 'jars', title: 'The Market & Jars', grades: 'Grades K–12 · foundation', minutes: '5–7 min', desc: 'Build your first money plan by choosing what to spend now, save for later, and give to others.', color: '#1464F0' },
  { n: 2, badge: 'lemonade', title: 'The Lemonade Stand', grades: 'Grades K–12', minutes: '10–15 min', desc: 'Run a business by testing batches, price, open hours, the cost of your own work, demand, profit, and tax.', color: '#FFD700' },
  { n: 3, badge: 'budget', title: 'Budget Town', grades: 'Grades 3–12', minutes: '7–10 min', desc: 'Cover needs, compare wants, build a food basket, prepare for a surprise, and preview bonds as a fourth money category for older learners.', color: '#00DCA0' },
  { n: 4, badge: 'bank', title: 'The Bank of TAYU', grades: 'Grades 6–12', minutes: '7–10 min', desc: 'Choose accounts, compare debit and credit, manage borrowing, spot a scam, and use the CD as a bridge to bond lending.', color: '#7850F0' },
  { n: 5, badge: 'garden', title: 'Money Garden — Modules 5A + 5B', grades: 'Grades 6–12', minutes: 'Two separate 6–8 min modules', desc: 'Module 5A — Investing Foundations: research businesses, diversify, compare stock ownership with bond lending, and use evidence. Module 5B — Markets, Risk & Patience: handle surprises, warning signs, bond default/rate risk, hype, patience, and rebalancing.', color: '#00b37f', parts: [{ id: 'A', label: 'Module 5A', title: 'Investing Foundations', minutes: '6–8 min', desc: 'Research businesses, spread risk, compare stocks with bonds, and use evidence instead of price alone.', color: '#00b37f' }, { id: 'B', label: 'Module 5B', title: 'Markets, Risk & Patience', minutes: '6–8 min', desc: 'Protect ready cash, react to warning signs, understand bond risk and interest-rate effects, resist hype, practice patience, and rebalance.', color: '#7850F0' }], worldModule: 5 },
  { n: 6, badge: 'bond', title: 'Bond Street', grades: 'Grades 6–12', minutes: '6–8 min', desc: 'Carry your Money Garden value into Bond Street, lend across Treasury, municipal, and corporate bonds, compare safety stars and interest, and save your muni-bond choice for the tax callback.', color: '#6D9A4E', finale: true },
  { n: 7, badge: 'tax', title: 'The TAYU Tax Office', grades: 'Grades 6–12', minutes: '10–15 min', desc: 'Meet Rex and file a simplified practice tax return: gross income, deductions, brackets, effective rate, withholding, refund/amount due, civic services, and the conditional muni-bond callback.', color: '#FF8A3D', finale: true },
]
export const MODULE_COUNT = MODULE_CATALOG.length
export const WORLD_CHAPTER_COUNT = 5
export const EDUCATOR_GRADE_BANDS = [
  { title: 'Elementary School', grades: 'Grades K–5', color: '#1464F0', copy: 'Grades K–2 are recommended Modules 1–2. Grades 3–5 add Budget Town as Module 3.', currentModules: MODULE_CATALOG.filter((module) => [1, 2, 3].includes(module.n)), plannedModules: [] },
  { title: 'Middle School', grades: 'Grades 6–8', color: '#7850F0', copy: 'All seven core modules are available. Money Garden is split into Module 5A and 5B, followed by Bond Street in Module 6 and the Tax Office in Module 7.', currentModules: MODULE_CATALOG, plannedModules: ['Credit scores and debt', 'Insurance and risk', 'Careers, earnings, and benefits'] },
  { title: 'High School', grades: 'Grades 9–12', color: '#00a77a', copy: 'All seven core modules establish a shared baseline. Module 5A and 5B deepen investing decisions, Module 6 adds fixed income, and Module 7 completes the journey with a simplified tax return.', currentModules: MODULE_CATALOG, plannedModules: ['College costs and financial aid', 'Retirement and long-term investing', 'Fintech, fraud, and digital money', 'Personal financial roadmap'] },
]
