export const MODULE_CATALOG = [
  {
    n: 1,
    badge: 'jars',
    title: 'The Market & Jars',
    grades: 'Grades K–12 · foundation',
    minutes: '5–7 min',
    desc: 'Build your first money plan by choosing what to spend now, save for later, and give to others.',
    color: '#1464F0',
    fcps: ['Unit 2', 'Unit 8'],
    sol: ['EPF.1', 'EPF.16'],
    objective: 'Explain opportunity cost and create a spending, saving, and giving plan.',
    k2: { title: 'Money Jars', desc: 'You get some money. Choose some for now, some for later, and some to help.', objective: 'Tell why one choice means waiting for another choice.' },
  },
  {
    n: 2,
    badge: 'lemonade',
    title: 'The Lemonade Stand',
    grades: 'Grades K–12',
    minutes: '10–15 min',
    desc: 'Run a business by testing batches, price, open hours, the cost of your own work, demand, profit, and tax.',
    color: '#FFD700',
    fcps: ['Unit 5', 'Unit 14'],
    sol: ['EPF.2', 'EPF.3', 'EPF.4'],
    objective: 'Use supply, demand, revenue, fixed and variable costs, and profit margin to run a business.',
    k2: { title: 'Lemonade Stand', desc: 'Make lemonade, choose a price, and see what your stand earns.', objective: 'Count money in and money out, then tell if the stand earned money.' },
  },
  {
    n: 3,
    badge: 'budget',
    title: 'Budget Town',
    grades: 'Grades 3–12',
    minutes: '7–10 min',
    desc: 'Cover needs, compare wants, build a food basket, and prepare for a surprise.',
    color: '#00DCA0',
    fcps: ['Unit 2', 'Unit 8'],
    sol: ['EPF.10', 'EPF.11', 'EPF.16'],
    objective: 'Build a budget that separates needs and wants and prepares for an emergency.',
  },
  {
    n: 4,
    badge: 'bank',
    title: 'The Bank of TAYU',
    grades: 'Grades 6–12',
    minutes: '7–10 min',
    desc: 'Choose accounts, compare debit and credit, manage borrowing, and spot a scam.',
    color: '#7850F0',
    fcps: ['Unit 7', 'Unit 9'],
    sol: ['EPF.6', 'EPF.12', 'EPF.13'],
    objective: 'Compare bank accounts, debit and credit, borrowing costs, and scam warning signs.',
  },
  {
    n: 5,
    badge: 'garden',
    title: 'Money Garden — Modules 5A + 5B',
    grades: 'Grades 6–12',
    minutes: 'Two separate 6–8 min modules',
    desc: 'Module 5A — Investing Foundations: research businesses, diversify, and use evidence instead of price alone. Module 5B — Markets, Risk & Patience: handle surprises, warning signs, hype, patience, rebalancing, and the stock-versus-bond bridge.',
    color: '#00b37f',
    fcps: ['Unit 13'],
    sol: ['EPF.17'],
    objective: 'Research investments, diversify a portfolio, evaluate risk, and rebalance using evidence.',
    parts: [
      { id: 'A', label: 'Module 5A', title: 'Investing Foundations', minutes: '6–8 min', desc: 'Research businesses, spread risk, and use evidence instead of price alone.', color: '#00b37f' },
      { id: 'B', label: 'Module 5B', title: 'Markets, Risk & Patience', minutes: '6–8 min', desc: 'Protect ready cash, react to warning signs, resist hype, practice patience, understand bond risk, and rebalance.', color: '#7850F0' },
    ],
    worldModule: 5,
  },
  {
    n: 6,
    badge: 'bond',
    title: 'Bond Street',
    grades: 'Grades 6–12',
    minutes: '6–8 min',
    desc: 'Enter Bond Street directly from the main TAYU town, compare Treasury, municipal, and corporate bonds, and interact inside the building.',
    color: '#6FA44A',
    fcps: ['Unit 13'],
    sol: ['EPF.8', 'EPF.17'],
    objective: 'Compare government and corporate bonds by issuer, maturity, return, and credit risk.',
    worldModule: 6,
  },
  {
    n: 7,
    badge: 'tax',
    title: 'TAYU Tax Office',
    grades: 'Grades 6–12',
    minutes: '10–15 min',
    desc: 'Preview the separate physical TAYU Tax Office after Bond Street and work through the in-world tax stations before the Finale.',
    color: '#FF8A3D',
    fcps: ['Unit 11'],
    sol: ['EPF.8', 'EPF.15'],
    objective: 'Read a W-2 and distinguish wages, withholding, deductions, credits, refunds, and tax due.',
    worldModule: 7,
    physicalDestination: true,
    underConstruction: true,
    leadsToFinale: true,
  },
]

export const CURRICULUM_COVERAGE = [
  ['1. Identifying Interests Explorations', 'Expansion', 'First Paycheck'],
  ['2. Goal Setting', 'Strong', 'Modules 1 and 3'],
  ['3. Post-Secondary Financial Support', 'Gap', 'Future module'],
  ['4. Exploring Post-Secondary Options', 'Expansion', 'First Paycheck'],
  ['5. Career and Employment Options', 'Expansion', 'Module 2 + First Paycheck'],
  ['6. Applying to a Job', 'Expansion', 'First Paycheck'],
  ['7. Financial Institutions and Regulatory Agencies', 'Strong', 'Module 4'],
  ['8. Budgeting and Consumer Skills', 'Strong', 'Modules 1 and 3'],
  ['9. Credit', 'Partial', 'Module 4'],
  ['10. Housing and Transportation', 'Partial', 'The Rainy Day'],
  ['11. Taxes', 'Strong', 'Modules 2 and 7'],
  ['12. Insurance', 'Expansion', 'The Rainy Day'],
  ['13. Retirement and Investments', 'Strong', 'Modules 5 and 6'],
  ['14. Business Background', 'Partial', 'Module 2'],
  ['15. Macroeconomics', 'Expansion', 'The Big Picture'],
  ['16. Capstone - Life Scenario', 'Strong', 'Certificate capstone'],
]

export const EXPANSION_MODULES = [
  { id: 'first-paycheck', title: 'First Paycheck', grades: 'Grades 6-12', fcps: 'FCPS Units 1, 4, 5, 6', sol: 'EPF.4, EPF.15', summary: 'Choose a role, compare training and pay, complete a practice W-4, and reconcile gross and net pay.' },
  { id: 'rainy-day', title: 'The Rainy Day', grades: 'Grades 6-12', fcps: 'FCPS Units 10, 12', sol: 'EPF.14', summary: 'Compare renting and owning, choose coverage, and experience the same emergency with and without insurance.' },
  { id: 'big-picture', title: 'The Big Picture', grades: 'Grades 9-12', fcps: 'FCPS Unit 15', sol: 'EPF.5, EPF.7, EPF.9', summary: 'See inflation reduce buying power and connect interest-rate changes, jobs, trade, and bond values.' },
]

export const MODULE_COUNT = MODULE_CATALOG.length
export const WORLD_CHAPTER_COUNT = 5

export const EDUCATOR_GRADE_BANDS = [
  {
    title: 'Elementary School', grades: 'Grades K–5', color: '#1464F0',
    copy: 'Grades K–2 are recommended Modules 1–2. Grades 3–5 add Budget Town as Module 3.',
    currentModules: MODULE_CATALOG.filter((module) => [1, 2, 3].includes(module.n)),
    plannedModules: [],
  },
  {
    title: 'Middle School', grades: 'Grades 6–8', color: '#7850F0',
    copy: 'All seven core modules are available. Money Garden is split into 5A and 5B, followed by Bond Street in the main town, the TAYU Tax Office, then the Finale.',
    currentModules: MODULE_CATALOG,
    plannedModules: ['Credit scores and debt', 'Insurance and risk', 'Careers, earnings, and benefits'],
  },
  {
    title: 'High School', grades: 'Grades 9–12', color: '#00a77a',
    copy: 'All seven core modules establish a shared baseline. Bond Street is part of the main TAYU town, followed by the TAYU Tax Office and Finale.',
    currentModules: MODULE_CATALOG,
    plannedModules: ['College costs and financial aid', 'Retirement and long-term investing', 'Fintech, fraud, and digital money', 'Personal financial roadmap'],
  },
]
