import { useMemo } from 'react'
import { BOND_TYPES, useBondStreet } from './bondStreetStore.js'

const money = (value) => `$${Math.round(Number(value || 0) * 100) / 100}`
const stars = (count) => '★'.repeat(count) + '☆'.repeat(Math.max(0, 3 - count))
function Shell({ eyebrow, title, children, onClose }) {
  return <div className="pointer-events-none fixed inset-0 z-[650]" data-bond-street-overlay="true"><section className="pointer-events-auto absolute right-[max(1rem,env(safe-area-inset-right,0px))] top-[calc(6.5rem+env(safe-area-inset-top,0px))] max-h-[calc(100dvh-8rem)] w-[min(31vw,24rem)] min-w-[19rem] overflow-y-auto rounded-3xl border-2 border-[#9bc36f] bg-[#fffdf6] p-4 text-navy shadow-2xl max-[899px]:bottom-[calc(8.5rem+env(safe-area-inset-bottom,0px))] max-[899px]:left-3 max-[899px]:right-3 max-[899px]:top-auto max-[899px]:max-h-[46dvh] max-[899px]:w-auto max-[899px]:min-w-0"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#4d7c3b]">{eyebrow}</div><h2 className="mt-1 font-display text-2xl font-extrabold">{title}</h2></div>{onClose && <button type="button" onClick={onClose} className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-navy/10 font-extrabold" aria-label="Close Bond Street panel">×</button>}</div>{children}</section></div>
}
function BondCard({ bond, amount, onAmount }) {
  return <div className="rounded-2xl border-2 border-navy/10 bg-white p-3"><div className="flex items-start justify-between gap-2"><div><div className="font-display text-lg font-extrabold">{bond.title}</div><div className="mt-1 text-sm font-black text-[#a06b00]" aria-label={`${bond.safety} out of 3 safety stars`}>{stars(bond.safety)}</div></div><div className="rounded-xl bg-[#edf7dd] px-2 py-1 text-xs font-extrabold">{Math.round(bond.rate * 100)}% practice interest</div></div><p className="mt-2 text-xs font-bold leading-snug text-navy/70">{bond.id === 'treasury' && 'You lend to the federal government. It is the safest example in TAYU, so it pays the least interest.'}{bond.id === 'muni' && 'You lend to a town, school district, or state for roads and schools. Its interest gets the special tax callback later.'}{bond.id === 'corporate' && 'You lend to a company. It pays more interest because a company can be a riskier borrower.'}</p><div className="mt-3 flex items-center justify-between gap-2"><button type="button" onClick={() => onAmount(amount - 1)} className="grid h-10 w-10 place-items-center rounded-xl bg-navy/10 font-display text-xl font-extrabold">−</button><div className="font-display text-xl font-extrabold">{money(amount)}</div><button type="button" onClick={() => onAmount(amount + 1)} className="grid h-10 w-10 place-items-center rounded-xl bg-navy/10 font-display text-xl font-extrabold">+</button></div></div>
}
export function BondStreetOverlay({ onFinish }) {
  const phase = useBondStreet((s) => s.phase), open = useBondStreet((s) => s.panelOpen), stake = useBondStreet((s) => s.stake), allocation = useBondStreet((s) => s.allocation), result = useBondStreet((s) => s.result), close = useBondStreet((s) => s.close), startAllocation = useBondStreet((s) => s.startAllocation), setAllocation = useBondStreet((s) => s.setAllocation), autoSplit = useBondStreet((s) => s.autoSplit), confirmAllocation = useBondStreet((s) => s.confirmAllocation), showHarvest = useBondStreet((s) => s.showHarvest), complete = useBondStreet((s) => s.complete)
  const total = useMemo(() => Object.values(allocation).reduce((sum, value) => sum + Number(value || 0), 0), [allocation])
  if (!open) return null
  if (phase === 'intro') return <Shell eyebrow="Module 6 · Bond Street" title="Beau teaches lending" onClose={close}><p className="mt-3 text-sm font-bold leading-relaxed">You finished the Money Garden with <strong>{money(stake)}</strong> of investing value to practice with here. Nothing resets: earning → budgeting → banking → investing → lending → taxes stays one connected journey.</p><div className="mt-3 rounded-2xl bg-[#edf7dd] p-3 text-sm font-bold leading-relaxed">A <strong>stock</strong> means ownership. A <strong>bond</strong> means lending money to a borrower who promises interest and repayment.</div><p className="mt-3 text-sm font-bold leading-relaxed">Beau: “Welcome to Bond Street. Three borrowers live here. Safer borrowers usually pay less interest; riskier borrowers may pay more.”</p><button type="button" onClick={startAllocation} className="mt-4 min-h-[52px] w-full rounded-2xl bg-[#4d7c3b] px-4 font-extrabold text-white">Meet the three borrowers →</button></Shell>
  if (phase === 'allocate') return <Shell eyebrow="BN3 · Build the Bond Meadow" title={`Lend all ${money(stake)}`} onClose={close}><p className="mt-2 text-xs font-bold leading-relaxed text-navy/65">Treasury = safer/lower interest. Corporate = higher interest/more borrower risk. Muni = local-government lending with a tax connection.</p><div className="mt-3 grid gap-3">{BOND_TYPES.map((bond) => <BondCard key={bond.id} bond={bond} amount={allocation[bond.id]} onAmount={(value) => setAllocation(bond.id, value)} />)}</div><div className={`mt-3 rounded-xl px-3 py-2 text-sm font-extrabold ${Math.round(total) === Math.round(stake) ? 'bg-teal/15' : 'bg-sun/20'}`}>Allocated: {money(total)} / {money(stake)}</div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={autoSplit} className="min-h-[48px] rounded-xl bg-navy/10 px-3 text-sm font-extrabold">Try balanced split</button><button type="button" disabled={Math.round(total) !== Math.round(stake)} onClick={confirmAllocation} className="min-h-[48px] rounded-xl bg-[#4d7c3b] px-3 text-sm font-extrabold text-white disabled:opacity-40">Plant the Bond Meadow!</button></div></Shell>
  if (phase === 'results' && result) return <Shell eyebrow="BN3c–BN5d · Outcome cards" title="The borrowers report back" onClose={close}><div className="mt-3 grid gap-3">{BOND_TYPES.map((bond) => { const principal = Number(allocation[bond.id] || 0), interest = Math.round(principal * bond.rate * 100) / 100; return <div key={bond.id} className="rounded-2xl border-2 border-navy/10 bg-white p-3"><div className="flex items-center justify-between gap-2"><strong>{bond.title}</strong><span className="font-black text-[#a06b00]">{stars(bond.safety)}</span></div><p className="mt-1 text-xs font-bold text-navy/65">Lent {money(principal)} · earned {money(interest)} interest · borrower paid as promised.</p></div> })}</div><div className="mt-3 rounded-2xl bg-[#fff2cf] p-3 text-sm font-bold leading-relaxed">Bondholders generally get paid before stockholders if a company fails. That higher claim helps explain why bonds usually move less than stocks, but corporate bonds can still default.</div><div className="mt-3 rounded-2xl bg-brandpurple/10 p-3 text-sm font-bold leading-relaxed">Interest-rate twist: when new rates rise, an older lower-rate bond can drop in market price because newer bonds pay more. If the borrower keeps paying and you hold to the promised end, the temporary price move matters less.</div><button type="button" onClick={showHarvest} className="mt-4 min-h-[52px] w-full rounded-2xl bg-[#4d7c3b] px-4 font-extrabold text-white">See my Bond Street harvest →</button></Shell>
  if (phase === 'harvest' && result) return <Shell eyebrow="Bond harvest" title={`${money(result.principal)} → ${money(result.finish)}`} onClose={close}><p className="mt-3 text-sm font-bold leading-relaxed">Bond Meadow result: you lent <strong>{money(result.principal)}</strong> and earned <strong>{money(result.interest)}</strong> in practice interest.</p><div className="mt-3 rounded-2xl bg-teal/10 p-3 text-sm font-bold leading-relaxed">Your stocks wiggled. Your bonds paid on time in this practice round. The bond allocation added a steadier part to the investing journey.</div>{result.muniInvested && <div className="mt-3 rounded-2xl border-2 border-teal/40 bg-white p-3 text-sm font-bold">Muni flag saved ✓ Rex will recognize your municipal-bond investment in the Tax Office.</div>}<p className="mt-3 text-sm font-bold leading-relaxed">Beau: “Now tell someone the difference: a stock is ownership; a bond is a loan.”</p><button type="button" onClick={() => { complete(); onFinish?.() }} className="mt-4 min-h-[52px] w-full rounded-2xl bg-electric px-4 font-extrabold text-white">To the Tax Office! →</button></Shell>
  return null
}
